site_url: "https://talentlynx.pages.dev"
search: false
backend:
  name: github
  repo: svenschu/talentlynx
  branch: main
  base_url: "https://decap-proxy.simplexo.de"

media_folder: "/src/assets"
public_folder: "/public"

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Veröffentlichungsdatum", name: "date", widget: "datetime" }
      - { label: "Inhalt", name: "body", widget: "markdown" }
